"""nodns -- Local DNS cache of nodns records via dnsmasq zone polling.

Polls the nodns bot's zone export API at a configurable interval and writes
A/AAAA records to /etc/dnsmasq.d/nodns.hosts (dnsmasq addn-hosts format),
then reloads dnsmasq via SIGHUP. This gives the router a local DNS cache of
all nodns records without needing a Nostr client, WebSocket connection, or
heavy dependencies -- only curl and sh, both in base OpenWrt.

The procd service (/etc/init.d/nodns-bridge) runs /usr/bin/nodns-poll.sh
with respawn, so it survives reboot and crashes.
"""
from __future__ import annotations

from typing import Any

from profile.ops import (
    BlankLine,
    Comment,
    Op,
    ServiceAction,
    ShellCommand,
    UciAddList,
    UciCommit,
    render_shell,
)
from shell_safe import int_range

from . import ParamDef, UseCase, register

# -- procd init script (static) -----------------------------------------------
# START=99 ensures it launches late in the boot sequence (after dnsmasq).
# respawn makes procd restart the poll loop if it exits unexpectedly.

_INITD_SCRIPT = """\
#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
\tprocd_open_instance
\tprocd_set_param command /usr/bin/nodns-poll.sh
\tprocd_set_param respawn
\tprocd_set_param stdout 1
\tprocd_set_param stderr 1
\tprocd_close_instance
}
"""

# -- poll script template -----------------------------------------------------
# Placeholders __ZONE__, __API_URL__, __POLL_INTERVAL__ are replaced at
# configure time. The script is written via a quoted heredoc on-device, so
# all shell/awk syntax is preserved literally.
#
# The awk one-liner parses the BIND zone file format emitted by the bot's
# /api/zone/{zone}/export endpoint:
#   $ORIGIN nodns.shop.
#   $TTL 3600
#
#   npub1abc\tIN\tA\t3600\t1.2.3.4
#   @\t     IN\tA\t3600\t10.0.0.1
#   alice\t IN\tAAAA\t3600\t2001:db8::1
#
# Only A and AAAA records are extracted (addn-hosts format has no TXT/MX).
# @ (zone apex) is expanded to the bare zone name. Relative names get the
# zone appended. FQDNs (trailing dot) are de-dotted.

_POLL_SCRIPT = """\
#!/bin/sh
# nodns DNS bridge -- polls zone export API, updates dnsmasq addn-hosts cache.
# Auto-generated by conwrt use_cases/nodns.
ZONE="__ZONE__"
API_URL="__API_URL__"
POLL_INTERVAL=__POLL_INTERVAL__
HOSTS_FILE="/etc/dnsmasq.d/nodns.hosts"
TMP_FILE="/tmp/nodns-zone.txt"

mkdir -p /etc/dnsmasq.d

while true; do
\t# Fetch BIND zone file from the nodns bot API.
\tif curl -s --connect-timeout 10 --max-time 30 \\
\t\t"${API_URL}/api/zone/${ZONE}/export" \\
\t\t-o "$TMP_FILE" 2>/dev/null; then
\t\t# Parse: extract A/AAAA records -> "ip<TAB>fqdn" lines for addn-hosts.
\t\tawk -v z="$ZONE" '
\t\tBEGIN { OFS = "\\t" }
\t\t{
\t\t\trtype = toupper($3)
\t\t\tif (rtype != "A" && rtype != "AAAA") next
\t\t\tname = $1
\t\t\tip = $NF
\t\t\tif (name == "@") name = z
\t\t\telse if (name ~ /\\.$/) sub(/\\.$/, "", name)
\t\t\telse name = name "." z
\t\t\tprint ip, name
\t\t}' "$TMP_FILE" > "$HOSTS_FILE.new"
\t\t# Atomic swap only when we got valid data.
\t\tif [ -s "$HOSTS_FILE.new" ]; then
\t\t\tmv "$HOSTS_FILE.new" "$HOSTS_FILE"
\t\t\tkillall -HUP dnsmasq 2>/dev/null
\t\telse
\t\t\trm -f "$HOSTS_FILE.new"
\t\tfi
\tfi
\tsleep "$POLL_INTERVAL"
done
"""


def _resolve_params(params: dict[str, Any]) -> dict[str, Any]:
    zone = str(params.get("zone", "nodns.shop"))
    api_url = str(params.get("api_url", "https://nodns.shop"))
    poll_interval = int_range(
        params.get("poll_interval", 300), "poll_interval", 60, 86400
    )
    if not api_url.startswith(("https://", "http://")):
        raise ValueError(
            f"api_url must start with https:// or http://, got: {api_url!r}"
        )
    if not zone or any(c.isspace() for c in zone):
        raise ValueError(f"zone must not be empty or contain spaces: {zone!r}")
    return {
        "zone": zone,
        "api_url": api_url,
        "poll_interval": poll_interval,
    }


def _build_nodns_ops(params: dict[str, Any]) -> list[Op]:
    r = _resolve_params(params)
    zone = r["zone"]
    api_url = r["api_url"]
    poll_interval = r["poll_interval"]

    poll_script = (
        _POLL_SCRIPT.replace("__ZONE__", zone)
        .replace("__API_URL__", api_url)
        .replace("__POLL_INTERVAL__", str(poll_interval))
    )

    return [
        Comment(text="--- nodns DNS bridge: local zone cache via dnsmasq ---"),
        ShellCommand(command="mkdir -p /etc/dnsmasq.d"),
        ShellCommand(command="touch /etc/dnsmasq.d/nodns.hosts"),
        BlankLine(),
        Comment(text="--- procd service: /etc/init.d/nodns-bridge ---"),
        ShellCommand(
            command="cat > /etc/init.d/nodns-bridge << 'NODNS_INIT_EOF'\n"
            + _INITD_SCRIPT
            + "NODNS_INIT_EOF"
        ),
        ShellCommand(command="chmod +x /etc/init.d/nodns-bridge"),
        BlankLine(),
        Comment(text="--- poll script: /usr/bin/nodns-poll.sh ---"),
        ShellCommand(
            command="cat > /usr/bin/nodns-poll.sh << 'NODNS_POLL_EOF'\n"
            + poll_script
            + "NODNS_POLL_EOF"
        ),
        ShellCommand(command="chmod +x /usr/bin/nodns-poll.sh"),
        BlankLine(),
        Comment(text="--- Register addn-hosts with dnsmasq ---"),
        ShellCommand(
            command=(
                "uci -q del_list dhcp.@dnsmasq[0].addnhosts="
                "'/etc/dnsmasq.d/nodns.hosts'; true"
            )
        ),
        UciAddList(
            config="dhcp",
            section="@dnsmasq[0]",
            option="addnhosts",
            value="/etc/dnsmasq.d/nodns.hosts",
        ),
        UciCommit(config="dhcp"),
        ServiceAction(name="dnsmasq", action="restart"),
        BlankLine(),
        Comment(text="--- Enable and start nodns-bridge ---"),
        ServiceAction(name="nodns-bridge", action="enable"),
        ServiceAction(name="nodns-bridge", action="start"),
        ShellCommand(
            command=f'echo "nodns bridge configured: zone={zone} '
            f'interval={poll_interval}s url={api_url}"'
        ),
    ]


register(UseCase(
    name="nodns",
    description=(
        "Local DNS cache of nodns records via dnsmasq. "
        "Polls the nodns bot zone export API and writes A/AAAA records to "
        "/etc/dnsmasq.d/nodns.hosts (dnsmasq addn-hosts). "
        "No extra packages required -- uses only curl and sh from base OpenWrt."
    ),
    packages=[],
    packages_remove=[],
    params={
        "zone": ParamDef(
            type=str, default="nodns.shop",
            description="DNS zone to cache (e.g. nodns.shop)",
        ),
        "api_url": ParamDef(
            type=str, default="https://nodns.shop",
            description="nodns bot API base URL (must start with https:// or http://)",
        ),
        "poll_interval": ParamDef(
            type=int, default=300, min_value=60, max_value=86400,
            description="Polling interval in seconds (min 60, max 86400, default 300)",
        ),
    },
    build_configure=lambda p: render_shell(_build_nodns_ops(p)),
    build_configure_ops=_build_nodns_ops,
    configure_via="ssh",
    test_status="untested",
    tested_notes="BusyBox shell only, needs on-device validation",
    requires_capabilities=[],
))
