#!/bin/sh
# nodns-bridge-install -- Install nodns DNS bridge on an existing OpenWrt router.
#
# Creates a procd service that polls the nodns bot zone export API and writes
# A/AAAA records to /etc/dnsmasq.d/nodns.hosts (dnsmasq addn-hosts format).
#
# Usage:
#   ssh root@router 'sh -s' < scripts/nodns-bridge-install.sh [zone] [api_url] [poll_interval]
#
# Or copy to the router and run locally:
#   sh nodns-bridge-install.sh [zone] [api_url] [poll_interval]
#
# Arguments (all optional, shown with defaults):
#   zone            nodns.shop
#   api_url         https://nodns.shop
#   poll_interval   300  (seconds, min 60)
#
# Requirements: curl in base OpenWrt. No extra packages needed.
# Works with 32MB RAM routers. BusyBox sh/awk/grep/sed only.

set -e

ZONE="${1:-nodns.shop}"
API_URL="${2:-https://nodns.shop}"
POLL_INTERVAL="${3:-300}"

# --- Validate args ---
case "$API_URL" in
    https://*) ;;
    http://*)  ;;
    *) echo "ERROR: api_url must start with https:// or http:// (got: $API_URL)"; exit 1 ;;
esac

if [ "$POLL_INTERVAL" -lt 60 ] 2>/dev/null; then
    echo "ERROR: poll_interval must be >= 60 (got: $POLL_INTERVAL)"
    exit 1
fi

echo "==> Installing nodns DNS bridge"
echo "    Zone:          $ZONE"
echo "    API URL:       $API_URL"
echo "    Poll interval: ${POLL_INTERVAL}s"

# --- Create directories ---
mkdir -p /etc/dnsmasq.d
touch /etc/dnsmasq.d/nodns.hosts

# --- Write procd init script (static, no config values) ---
echo "==> Writing /etc/init.d/nodns-bridge"
cat > /etc/init.d/nodns-bridge << 'NODNS_INIT_EOF'
#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/nodns-poll.sh
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
NODNS_INIT_EOF
chmod +x /etc/init.d/nodns-bridge

# --- Write poll script (quoted heredoc, then sed placeholders) ---
echo "==> Writing /usr/bin/nodns-poll.sh"
cat > /usr/bin/nodns-poll.sh << 'NODNS_POLL_EOF'
#!/bin/sh
# nodns DNS bridge -- polls zone export API, updates dnsmasq addn-hosts cache.
# Auto-generated by nodns-bridge-install.sh.
ZONE="__ZONE__"
API_URL="__API_URL__"
POLL_INTERVAL=__POLL_INTERVAL__
HOSTS_FILE="/etc/dnsmasq.d/nodns.hosts"
TMP_FILE="/tmp/nodns-zone.txt"

mkdir -p /etc/dnsmasq.d

while true; do
	# Fetch BIND zone file from the nodns bot API.
	if curl -s --connect-timeout 10 --max-time 30 \
		"${API_URL}/api/zone/${ZONE}/export" \
		-o "$TMP_FILE" 2>/dev/null; then
		# Parse: extract A/AAAA records -> "ip<TAB>fqdn" lines for addn-hosts.
		awk -v z="$ZONE" '
		BEGIN { OFS = "\t" }
		{
			rtype = toupper($3)
			if (rtype != "A" && rtype != "AAAA") next
			name = $1
			ip = $NF
			if (name == "@") name = z
			else if (name ~ /\.$/) sub(/\.$/, "", name)
			else name = name "." z
			print ip, name
		}' "$TMP_FILE" > "$HOSTS_FILE.new"
		# Atomic swap only when we got valid data.
		if [ -s "$HOSTS_FILE.new" ]; then
			mv "$HOSTS_FILE.new" "$HOSTS_FILE"
			killall -HUP dnsmasq 2>/dev/null
		else
			rm -f "$HOSTS_FILE.new"
		fi
	fi
	sleep "$POLL_INTERVAL"
done
NODNS_POLL_EOF
chmod +x /usr/bin/nodns-poll.sh

# Inject config values (use | delimiter to handle URLs containing /).
sed -i \
	-e "s|__ZONE__|$ZONE|g" \
	-e "s|__API_URL__|$API_URL|g" \
	-e "s|__POLL_INTERVAL__|$POLL_INTERVAL|g" \
	/usr/bin/nodns-poll.sh

# --- Register addn-hosts with dnsmasq ---
echo "==> Configuring dnsmasq addn-hosts"
uci -q del_list dhcp.@dnsmasq[0].addnhosts='/etc/dnsmasq.d/nodns.hosts' || true
uci add_list dhcp.@dnsmasq[0].addnhosts='/etc/dnsmasq.d/nodns.hosts'
uci commit dhcp
/etc/init.d/dnsmasq restart

# --- Enable and start bridge service ---
echo "==> Starting nodns-bridge service"
/etc/init.d/nodns-bridge enable
/etc/init.d/nodns-bridge start

echo ""
echo "==> nodns DNS bridge installed successfully"
echo "    Cache file:   /etc/dnsmasq.d/nodns.hosts"
echo "    Polling:      ${API_URL}/api/zone/${ZONE}/export every ${POLL_INTERVAL}s"
echo "    Service:      /etc/init.d/nodns-bridge (procd, auto-respawn)"
echo ""
echo "Verify after first poll cycle:"
echo "    nslookup test.${ZONE} 127.0.0.1"
